[features]
seeds = false
skip-lint = false

[programs.devnet]
death_protocol = "EMmqYXyEiJuBqSQFkpsXJLPPZVj6LbiaThEyMNgrYzXD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/drippy/.config/solana/id.json"

[scripts]
test = "vitest"

[test]
startup_wait = 15000
validator = { cmd = "solana-test-validator" }
